export const techNameMap: { [key: string]: string } = {
  'tailwind': 'Tailwind CSS',
  'typescript': 'TypeScript',
  'javascript': 'JavaScript',
  'html5': 'HTML5',
  'css3': 'CSS3',
  'react': 'React',
  'next': 'Next',
  'git': 'Git',
  'github': 'GitHub',
  'linux': 'Linux',
  'powershell': 'PowerShell',
  'python': 'Python',
  'java': 'Java',
  'c#': 'C#',
  'mysql': 'MySQL',
  'postgresql': 'PostgreSQL',
  'unity': 'Unity',
  'godot': 'Godot',
  'docker': 'Docker',
  'figma': 'Figma',
  'angular': 'Angular',
  'bootstrap': 'Bootstrap',
  'affinity studio': 'Affinity Studio',
  'photoshop': 'Photoshop',
  'illustrator': 'Illustrator',
  'canva': 'Canva',
  'krita': 'Krita',
  'blender': 'Blender',
  'react native': 'React Native',
  'flutter': 'Flutter'
};
